apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend-sa
      containers:
      - name: backend-container
        image: asia-southeast1-docker.pkg.dev/terraform-new-465907/backend/backend:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "150m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
