apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'backend'
        vault.hashicorp.com/agent-inject-secret-app-secrets.env: 'secret/data/backend/app'
        vault.hashicorp.com/agent-inject-template-app-secrets.env: |
          {{- with secret "secret/data/backend/app" -}}
          {{- range $k, $v := .Data.data }}
          {{ $k }}={{ $v }}
          {{- end }}
          {{- end }}
    spec:
      serviceAccountName: backend-sa
      containers:
      - name: backend-container
        image: asia-southeast1-docker.pkg.dev/terraform-new-465907/backend/backend:latest
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: app-secrets.env
        resources:
          requests:
            cpu: "20m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
